name: Var_Context_Workflow_Demo
on:
    workflow_dispatch:
env:
    # Setting an environment variable with the value of a configuration variable
    env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
    display-variables:
      runs-on: ubuntu-latest
      steps:
      - name: Use variables
        run: |
          echo "name: ${{ vars.JOB_NAME }}"