name: build_json
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"Chapter1\",\"config\":\"Test\"},{\"project\":\"Chapter2\",\"config\":\"Debug\"},{\"project\":\"Three\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: |
         echo "${{ fromJSON(needs.job1.outputs.matrix).project }}"
         echo "${{ fromJSON(needs.job1.outputs.matrix).config }}"