name: expressions-example
on:
  push:
  pull_request:

jobs:
  use-expressions:
    strategy:
      matrix:
        greeting: [Hello, Howdy, Hey]
    runs-on: ubuntu-latest
    steps:
      -
        name: Print if 'Hello'
        if: ${{ matrix.greeting == 'Hello' }}
        run: echo "greeting is Hello"
      -
        name: Print if starts with 'He'
        if: ${{ startsWith(matrix.greeting, 'He') }}
        run: echo "greeting starts with He"
      -
        name: Print if ends with 'y'
        if: ${{ endsWith(matrix.greeting, 'y') }}
        run: echo "greeting ends with y"
      -
        name: Print if contains 'ow'
        if: ${{ contains(matrix.greeting, 'ow') }}
        run: echo "greeting contains ow"
      -
        name: Print formatted greeting
        run: |
          echo "${{ format('{0} says {1}', github.actor, matrix.greeting) }}"
      -
        name: To JSON
        run: echo 'Job context is ${{ toJSON(job) }}'
      -
        name: Success
        if: ${{ success() }}
        run: echo "Still running..."
      -
        name: Always
        if: ${{ always() }}
        run: echo "You will always see this"
      -
        name: Canceled
        if: ${{ cancelled() }}
        run: echo "You canceled the workflow"
      -
        name: Failure
        if: ${{ failure() }}
        run: echo "Something went wrong..."

      - id: set_var
        run: |
            content=`cat ./path/to/package.json`
            # the following lines are only required for multi line json
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            # end of optional handling for multi line json
            echo "::set-output name=packageJson::$content"
            echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"


