name: expressions_github_actions
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    myNull: ${{ null }}
    myBoolean: ${{ false }}
    myIntegerNumber: ${{ 711 }}
    myFloatNumber: ${{ -9.2 }}
    myHexNumber: ${{ 0xff }}
    myExponentialNumber: ${{ -2.99e-2 }}
    myString: Mona the Octocat
    myStringInBraces: ${{ 'It''s open source!' }}


jobs:
  show-values:
    runs-on: ubuntu-latest
    steps:
     - name: print value
       run: |
         echo ${{env.myNull}}
         echo ${{env.myBoolean}}
         echo ${{env.myIntegerNumber}}
         echo ${{env.myFloatNumber}}
         echo ${{env.myHexNumber}}
         echo ${{env.myExponentialNumber}}
         echo ${{env.myStringInBraces}}
