name: function_github_actions
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  show-values:
    runs-on: ubuntu-latest
    steps:
     - name: is Hello World contains wo
       run: echo ${{ contains('Hello world', 'wo') && 'Yes' || 'No' }}