name: Basic Job Context
on: [push]

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Job Context
        run: |
         echo "All about JOB=${{toJSON(job)}}"
         echo "Job Name=${{github.job}}"


