name: Basic Job Context
on: [push]

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Job Context
        run: |
         echo "All about JOB=${{toJSON(job)}}"
         echo "Job Name=${{github.job}}"
         echo "Job Container=${{github.job.container}}"
         echo "Job Container=${{github.job.container.id}}"
         echo "Job Container=${{github.job.container.network}}"
         echo "Job Container=${{github.job.services}}"
         echo "Job Container=${{github.job.services.id}}"
         echo "Job Container=${{github.job.services.network}}"
         echo "Job Container=${{github.job.services.ports}}"
         echo "Job Container=${{job.status}}"



