name: Basic Job Context
on: [push]

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Job Context
        run: |
         echo "All about JOB=${{toJSON(job)}}"
         echo "Job Name=${{github.job}}"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Step
        if: github.job == 'job1'
        run: echo "This step runs only for job1"

  job2:
    runs-on: windows-latest
    steps:
      - name: Conditional Step
        if: github.job == 'job2'
        run: echo "This step runs only for job2"

  custom-name-job:
    name: Custom Name Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Custom Job Name
        run: echo "Custom Job Name= $github.job"

  generate-output:
    runs-on: ubuntu-latest
    outputs:
      generated-value: ${{ steps.step1.outputs.value }}
    steps:
      - name: Generate Value
        id: step1
        run: echo "::set-output name=value::GITHUBACTIONS"

  use-output:
    runs-on: ubuntu-latest
    needs: generate-output
    steps:
      - name: Use Generated Value
        run: echo "Generated Value= ${{ needs.generate-output.outputs.generated-value }}"



