name: Basic Job Context
on: [push]

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Job Context
        run: |
         echo "All about JOB=${{job}}"
         echo "Job Name=${{github.job}}"


