name: json_view
on:
  push:
    branches: [ "main" ]
jobs:
  build-with-step:
    runs-on: ubuntu-latest
    steps:
      - id: get_json_data
        run: |
          file_path="$GITHUB_WORKSPACE/src/main.cpp"
          echo "File path: $file_path"