name: Multi-Job Workflow with Env Sharing

on: [push]

jobs:
  data:
    runs-on: ubuntu-latest
    outputs:
        ENV_VAR_D: ${{ steps.set-env-var.outputs.ENV_VAR }}
    steps:
      - name: data
        id: set-env-var
        run: echo "::set-output name=ENV_VAR::hello"
  build:
    needs: data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: print env value
        run: |
          echo "$GITHUB_ENV"
          echo "Environment Variable from Job 1: ${{ needs.data.outputs.ENV_VAR_D }}"

