name: Print Runner OS
on: [push]

jobs:
# Print Runner OS:
  print-runner-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Print Runner OS
        run: echo "Runner OS= ${{ runner.os }}"
# Print Runner Details:
  print-runner-Details:
    runs-on: ubuntu-latest
    steps:
      - name: Print Runner Labels
        run: echo "Runner Labels= ${{ toJson(runner)}}"
      - name: Print Runner IP Address
        run: |
          ip route get 1 | awk '{print $NF;exit}'
          echo "-------"
          curl -s https://api.ipify.org
          echo "-------"
          hostname -I | cut -d' ' -f1

  docker-job:
    runs-on: ubuntu-latest
    container:
        image: windows-latest
    steps:
      - name: Print Runner OS in Docker
        run: echo "Runner OS= ${{ runner.os }}"
