name: Generate random failure
on: push
jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 0 or 1
        id: generate_number
        run:  |
            echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
            echo "random_number=$(($RANDOM % 2))"
      - name: Pass or fail
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then 
          echo "OutPut=${{ steps.generate_number.outputs.random_number }}"
          exit 0;
          else
          echo "OutPut=${{ steps.generate_number.outputs.random_number }}"
          exit 1;
          fi
